### ISSUE TITLE
[ADDITION] Hemmelig.app - Encrypted sensitive data sharing platform

### ISSUE THREAD

**Issue by bjarneo** [Lissy93/awesome-privacy#169]
### Category

Communication? Encrypted sensitive data/password sharing

### Software to be added

Hemmelig.app
This software encrypts sensitive data at the client side, and makes it possible to share it securely over mail, slack, teams, messenger or similar. It is available as a saas or as self hosted.

### Supporting Material

https://github.com/HemmeligOrg/Hemmelig.app

### Association Disclosure

I am the owner

### Would you like to submit a PR?

Maybe?

### Please tick the boxes

- [X] You have filled out this form accurately, and to the best of your knowledge
- [X] You have indicated weather or not you are associated with the suggested addition
- [X] A similar submission has not already [been opened](https://github.com/Lissy93/awesome-privacy/issues?q=is%3Aissue) for this software/ service
- [X] You agree to the [code of conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by Lissy93** [comment]
This is an awesome little app, nice work!!

Maybe if I created a new section for Pastebins, do you think it could fit there?
Otherwise in the [Notable Mentions](https://github.com/Lissy93/awesome-privacy#other-notable-mentions) within the Encrypted Messengers section

P.S I love the little ROT13 message in the response header saying where to report vulnerabilities to ;)
