### ISSUE TITLE
[REMOVAL] Please remove filen from the list.

### ISSUE THREAD

**Issue by uncharted-user** [Lissy93/awesome-privacy#208]
### Title

FileN

### Removal Reason

I purchased their plan and been with filen for about more than a month. Their support is unresponsive of any issue. If you see their repository issues, then you will assume whether the project is dead! More than 7 months old issues are still waiting to be just answered. Their sub Reddit is a mess. You will be bombarded if even raise any issue with any bug. This repository is a sanctuary for me, but this purchase is causing me so much pain. Their app is terrible is quality and lack of basic requirements such as syncing all files properly. You will see there are corrupted and missing files here and there! There is no way to make sure all files are properly synced.

References:
1. https://www.reddit.com/r/filen_io/comments/1aiahl6/filen_app_development_speed_is_concerning/
2. https://github.com/FilenCloudDienste/filen-desktop/issues
3. https://github.com/FilenCloudDienste/filen-mobile/issues

### Association Disclosure

I am a paid user.

### Would you like to submit a PR?

Yes!

### Please tick the boxes

- [X] You have filled out this form accurately, and to the best of your knowledge
- [X] You have indicated whether or not you are associated with this project or a competitor
- [X] A similar submission has not already [been opened](https://github.com/Lissy93/awesome-privacy/issues?q=is%3Aissue) for this software/ service
- [X] You agree to the [code of conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by Lissy93** [comment]
Thanks @uncharted-user 
I'm looking into this. Do you know of anyone else whose had issues with Fillen. This is the first I've heard about problems with this service.

**Comment by Lissy93** [comment]
All the repos do look to be actively maintained, with tickets being triaged and addressed properly.
I'll look into this further, but maybe @Arcus-Filen @Dwynr or @DanielProg39 could share some insight as to where Filen's at the moment.

**Comment by DanielProg39** [comment]
I'm here to answer anything I can. Although I should point out that I am not a part of the Filen staff and I am not directly affiliated with them. However, I am a contributor, a Pro plan user and I follow the project closely so I consider myself to have a higher level of awareness of its state.

Where is Filen at the moment? Filen is being actively developed and the company is now facing significant operational changes, so the project is definitely not stale or dead. It may appear that way on the surface because most of the work is done behind the scenes, so there are no major developments in the public repos at the moment, apart from the recent development of a new mobile client version. Which, by the way, is part of the latest project update (and probably the biggest one yet), adding notes, chats and contacts to the web and mobile clients. The team is working on hiring more people and reorganising internal operations to better handle the maintenance of the service and the intensity of development. In terms of development, work is underway to implement workspaces (which are primarily for business, but some of the functionality will be available to consumers, as is already the case with chats and contacts, for example) and to make the service a more viable B2B option. There is another area of development that is more relevant to the author of this issue.

The user in question has complained that the desktop application does not work on his computer. It seems that he's upset that the developers haven't responded to his issue, and haven't fixed numerous others that, tldr, describe how the synchronisation is broken in numerous ways, which is entirely true. But there is a reason for all this. First of all - development of the desktop application has been stopped, which means that no issues or pull requests are being reviewed. Instead, a completely new desktop app is being developed internally, which will include a built-in file explorer and an option to mount cloud storage in addition to syncing. So yes, the desktop app has been abandoned and is unusable in some circumstances, but that doesn't mean there's no work going on, or worse, that the whole project is dead.

If you want a more detailed look at what's happening in the company, you can check out their [blog](https://blog.filen.io/).

If you have any further questions, feel free to ask.

P.S. I just checked out your project and I really like it, you get a star from me ;)
P.P.S. I have some comments about the cloud storage providers you listed, let me know if you are interested. Also, I can contribute by adding a number of applications and services across several topics.

**Comment by Lissy93** [comment]
Thank you so much Daniel, you're insight here is super helpful.
And kudos to you for all your work on Filen, I'd assumed you worked there, based on you being one of the top contributors on the web and mobile apps. Hats off to you 🫡


My stance on this, is that we keep Filen here. It's overall a very good service, meets the criteria in-terms of privacy, and though the quality issues mentioned by OP do sound unfortunate and frustrating, it sounds like these are being worked on, and will be resolved in due course. But of course, I'll keep an eye on this


> P.P.S. I have some comments about the cloud storage providers you listed, let me know if you are interested. Also, I can contribute by adding a number of applications and services across several topics.

Please, yes very interested! I'm (slowly) working my way through this list updating/removing/adding listings, but some of the categories (like cloud storage) is not my area of expertise. So I'd definitely love to hear any thoughts you have, or if there's anything I should edit/delete or add. PRs are also very welcome ;)

Thanks again, and have a good evening!

**Comment by DanielProg39** [comment]
I fully understand your concerns.

> There is also question about data integrity.

This is largely the problem with the desktop application, so the only viable option at the moment is to wait until the new one is released. For example, I don't use it anymore because it's unstable. Yes, it's less convenient, but I'm relatively fine with just using web and Android apps for now, because the syncing functionality isn't the main thing, it's the job of easily storing and managing files in the cloud that Filen is good at. The web and mobile apps do this quite well.

> Unfortunately, we users are not informed. Their unresponsiveness behavior is really frustrating as a paid user. It feels that we do not matter!

The lack of reliable and visible means of communication and information has been a major problem since the company's inception. I believe that if they had a better information strategy they could have a much larger user base and a much better informed community. At least they have started their blog, which is a significant step forward, but far from perfect. On the other hand, I can't really blame them, as almost all development is literally done by one person, and the team is physically unable to handle and respond to all the questions, problems and requests, despite their best efforts that may not be so visible on the surface. For example, Jan is too busy to respond to issues with the desktop application, especially as it's being abandoned and the new one is being developed, it's just not important enough to spend time on given the amount of work he and his team are doing. However, as I said earlier, there is work going on in the corporate structure that also aims to address these issues.

**Comment by DanielProg39** [comment]
I agree that it's irresponsible not to respond to customers' concerns and not to properly inform them about the state of development of the desktop application, it's the Filen staff's fault and nothing can fully justify it. BTW, the advice not to use the desktop client is my personal advice, you are free to use it as long as you don't have problems, I just wanted to point out that the developers are aware of the situation and are working on a new client.

My personal opinion on this situation: this is not the end of the world. Putting your users at risk of corrupted or missing files by not addressing the situation properly is definitely wrong and irresponsible. But synchronisation is not the main feature of the service and it doesn't significantly affect the overall quality of the service: it's secure, the speeds are great, the storage is reliable. That's what you'd expect from such a service in the first place, and it delivers what it promises, so while the problems with the desktop client and your feelings about the lack of response from the developers and the lack of information to customers may be valid reasons for you not to use it, they're not objective reasons for everyone not to use it.

**Comment by Lissy93** [comment]
I would like to add, that since this issue was raised, I signed up for, and downloaded Filen, tested it out across two computers, and I've not had any issues at all. Personally, I was quite impressed the the user experience and performance. 

That said, I fully understand the concerns raised, and have reopened the ticket. I think let's revisit in a month or two, to see if the quality issues have been addressed.

In the meantime, I've reached out to Filen customer support, so hopefully they'll be able to give some more insight into if/when these issues will be addressed. They've annoyingly disabled Twitter DMs, and don't have an email address or phone number, just one of those annoying web forms. So I guess if I don't hear back from them, that proves OPs point about them being unresponsive!

**Comment by DanielProg39** [comment]
Fair enough 👍

**Comment by DanielProg39** [comment]
> I've not had any issues at all

Me neither. I found a few minor inconsistencies, but nothing more than that. Mainly because I didn't sync many files. But things change when you have thousands of files and lots of subfolders, as some people do. The application is much more stable than it used to be and may still be suitable for many people. That's why I don't think the problems with the desktop application are a big deal for Filen; it can still be quite usable if you don't use it intensively and don't rely on it completely. But don't assume it's really stable, as some people are still experiencing problems. And it's the fact that many of those people are potentially those who rely on it to sync or back up a lot of potentially important files that makes it a problem. It's not a disaster and it's not completely broken, but it's not stable enough to be completely usable without major problems.

**Comment by Lissy93** [comment]
Reply from Filen support team is below 👇

> 
> Hello Alicia,
> 
> Thank you for contacting us.
> 
> Of course, the service is maintained.
> 
> We only recently set up our own complete server hardware infrastructure, including the corresponding data migration, which was one of the main reasons for the significantly delayed updates.
> Since we started as a small startup, without investor money, completely self-financed, the development is unfortunately a bit slower compared to other companies and when mega projects such as completely own servers are added, which have to be maintained in the long term due to the sustainability for the company in order not to be dependent on third-party data center providers (like larger competitors, for example), things have unfortunately been slow lately. We are also still in the hiring process so that the workload can be spread further and problems can be addressed and resolved more quickly. As mentioned, this is not meant to be an excuse, but only to explain why things have not been going so smoothly for some users recently.
> 
> In this regard, we had already published blog posts some time ago, which addressed the reason for delays etc:
> https://blog.filen.io/statusupdate-11-11-2023/
> https://blog.filen.io/status-update/
> 
> Due to the available resources, we rotate with the applications and the corresponding updates, which sometimes leads to longer delays in between the updates.
> This is also only because all the applications we offer are still being continuously expanded until all the planned features are implemented, as we first provided the website out of nowhere and then the other applications bit by bit.
> 
> The sync problems that have been mentioned come from a comparatively small group of users who naturally also want to get rid of their frustration. Of course this is annoying for both sides, but it is also difficult for us to reproduce these problems if there are not the same work environments and or the logs do not show any errors (for example storage access issues or network issues with the corresponding missing files) or the users either make operating errors or use other third party software, which also accesses the linked files and then interferes with our sync.
> 
> In addition, when we receive reports of problems, 90% of them come from Linux users, which is why we have explicitly pointed out in the corresponding downloads for Linux that the client currently only runs verified with the vanilla distributions Ubuntu/Debian (GNOME) (https://filen.io/apps). Many users use distributions that are not very widespread and unfortunately have to be pushed back due to the small number of users. In general, the access rate of users with Linux is 4-5%, which is why we unfortunately always prioritize the problems that affect the largest user group.
> 
> Of course, issues also occur on Windows and MacOS, which we do not forget to mention. But since we support 3 primary operating systems, we always do everything in one update and not one update for linux, one for Windows and one for MacOS.
> The same applies to the mobile app on Android and iOS.
> 
> We have been able to collect many bugs/issues in the last weeks and months and are now in the process of completely renewing the sync client (improved sync logic, virtual drive, WebDAV integration etc.) As mentioned, everything has been delayed more than planned (which is why we are not giving out any ETAs so as not to give false hope unnecessarily). The mobile update was also delayed more than planned, but is now finally available in the stores. This update was brought forward due to the higher demand, especially because of the automatic camera upload or the file provider integration, so that the desktop client will only go into the first beta phase in the coming weeks. Corresponding commits will also be available in the repository in the coming weeks.
> 
> We can only apologize for the delays that have occurred. 
> 
> No issue was forgotten or abandoned. It's just that due to the recent circumstances, restructuring and investments in the future security of the self hosted backend, everything has been delayed more than planned. 
> 
> I will forward your request so that the relevant team members can take a look at it.
> 
> Kind regards,
> Filen Support
> 
> 2/27/2024, 10:27:53 PM

**Comment by Lissy93** [comment]
I think it's fair to say, that based on their reply, @DanielProg39's input and the other info here, that Filen is still very much under active development, and they're aware and addressing the user experience issues. There's also not been any major privacy or security concerns, which is normally the primary reason for removing something.

So I'm going to close this ticket, and keep Filen on the list. But feel free to add any more details below, if anything else comes up.

✌️

**Comment by aednichols** [comment]
@DanielProg39 since you kindly offered to answer questions – are they building the new desktop client around the new [Typescript SDK repo](https://github.com/FilenCloudDienste/filen-sdk-ts) that is being furiously developed, including on weekends?

**Comment by DanielProg39** [comment]
Although I'm not entirely sure, I may have heard that they needed to build a new backend/SDK to better support new features like notes, contacts and chat for their desktop app and others. So basically the answer is yes.

But I must remind you that I am not a Filen representative and I am not fully aware of the internal developments and do not know much about the technical details of these developments. So take this with a grain of salt as I could be completely wrong.

**Comment by uncharted-user** [comment]
**Update:** I probably was too hard on them, but the situation is much better right now. Their apps are working to find, although some features are missing, such as minimize to tray instead of closing, no option to limit the file version, and some reports of high CPU usages on idle for Sequoia. The first two problems are added as enhancement for future release, and the third one needed further investigation. They seem much more active on GitHub too regarding addressing issues.
