### ISSUE TITLE
[REMOVAL] Remove Brave and Librewolf from the browser list

### ISSUE THREAD

**Issue by iio7** [Lissy93/awesome-privacy#5]
### State which point should be edited or removed. Put "Remove/ Edit ____" as Title

Remove Librewolf and Brave browser from the list.

### Justification

Neither are truly privacy respecting. Please see: https://www.unixsheikh.com/articles/choose-your-browser-carefully.html

**Comment by atomGit** [comment]
i perhaps should have mentioned for those that don't know, [LibreWolf benefits](https://gitlab.com/librewolf-community/settings) from the arkenfox user.js project

**Comment by JaydenDev** [comment]
Firefox has to tend to a large user-base. A user-base of frequent Google ecosystem users, some use Firefox for privacy. Not all though, the issue with making such a private/secure browser. Is that you have to tend to the _entire_ user-base. Not just those who seek privacy and security features.

**Comment by kdenhartog** [comment]
> But even so, even if the user understand the AdTech business and technology deeply enough to give an informed consent, such consent should always be explicit and opt-in.

Explicit consent that requires opt-in would mean that at startup every new user would need to explicitly select their choices for `about://config` (Firefox) or `brave://flags` (brave) or `chrome://flags` (chrome) on setup and then also recheck it every time a browser is updated to make sure no unintended side effects have been brought in. Otherwise, one could argue that a new browser couldn't render HTML5 (since [canvas elements can be used to fingerprint](https://en.wikipedia.org/wiki/Canvas_fingerprinting)) all JS would be turned off, and we'd end up with an even more [incompatible web platform](https://wpt.fyi/results/?label=experimental&label=master&aligned) compared to where we're at currently. I know that's not the argument you're making, but I point it out to show that the principle of `explicit and opt-in` can only be taken so far before it turns from a useful principle to a broken weapon. This is simply because of the complexity of trade offs that occur.

At some point, it's reasonable to accept that defaults will be set in order to accept tradeoffs between the extremes of usability (users can't configure anything and everything is handled for them by the developers) and consent (users have to configure everything and nothing is decided by the developer). Especially because it's a full time job to keep up with everything that browsers are changing. So to ask a user to do either one of those extremes seems unreasonable. This is why we have defaults in the first place, but also enable users to change them.

All in all, reasonable minds can differ on the same topic. Especially when it comes to incredibly nuanced topics such as privacy on the web and configuring a browser. However, I personally fall on the side that Librewolf and Brave should remain in this list because I think the net gains far outweigh the net losses to users. If others disagree with the outcome of this issue and @Lissy93 decision (whether these options stay or are removed) we always have the option to fork this repo and change it.

In any case, it was great to get other peoples take on this topic and I enjoyed hearing the differing perspectives of the values that motivates them as users, and presumably also developers since we're on GH, in choosing and building software.

**Comment by atomGit** [comment]
back to basics...

@iio7 justification for wanting to ax LibreWolf and Brave is because "Neither are truly privacy respecting"

he/she is correct, _if_ we assume default settings, and i don't think there's an argument there, but the same argument can be made for Firefox or any other modern browser, so the reason for wanting to eliminate LW and Brave specifically falls on its head right there (and i personally have serious concerns with Tor but that's another story)

no modern browser is truly privacy respecting out of the box, hence the need for projects like arkenfox ... and LibreWolf

**Comment by Lissy93** [comment]
There's been some good discussions here. For now, let's close this - as there aren't any serious privacy concerns regarding Brave (which are resolved in other browsers). But if anything changes, please do comment and I shall re-open.
