### ISSUE TITLE
[QUESTION]  Why using a password manager instead of google's chrome password manager?

### ISSUE THREAD

**Issue by Jujusp** [Lissy93/awesome-privacy#88]
### Your Question

After reading the musts on this Wiki, you recommended some password managers. I decided to use Bitwarden but now I am asking myself, why am I changing to Bitwarden if Google is already storing my passwords on chrome? Are there some benefits? This is the first time I have been worried about privacy and security so I don't know if this question is very dumb or if I am missing the point. 

### Please tick the boxes

- [X] You have filled out this form accurately, and to the best of your knowledge
- [X] A similar question has not already [been asked](https://github.com/Lissy93/awesome-privacy/issues?q=is%3Aissue) for this software/ service
- [X] You agree to the [code of conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by Lissy93** [comment]
Yeah, this is a good question. And the answer would depend on your threat model

I'd be interested to hear what others have to say, but the reason I personally would not do this, is because....
- You have to trust Google's privacy, and **they will** freely hand over your data to any government if they were asked
- You have to trust Google's security (likely fine), but there stuff isn't open source so it's harder to verify
- Google makes their profit out of data, so far every service they've offered has had an alterer motive around profiting from data. They don't have a great track record.
- There's a simple ducky script by JoeBurns to extract a users passwords, [here's the post](https://www.linkedin.com/posts/cyber-security-speaker-joe_hacking-cybersecurityawareness-passwords-activity-6731704512823861248-J5VB/)
  - But even a non-technical user could do something similar if your device is not locked, just head to `chrome://settings/passwords`, [here's example](https://www.techrepublic.com/article/why-you-should-never-allow-your-web-browser-to-save-your-passwords/)
  - Of if any of your devices get compromised, browser passwords will be the easiest to nab
- Ties you into Google ecosystem, you can't auto-fill Chrome passwords in Firefox for example
- Lack of features compared to a dedicated password manager. Viewing, sharing, auto-regeneration, 2FA, storing alternate data, etc is either hard or impossible with Google
- Single point of failure, any attacker who gets into your Google account has access to all of your other accounts
  - Especially if your signed on on phone, laptop, tablet, chromebook, etc and your device is stolen


Whereas dedicated password managers, are encrypted at rest, use open source code bases which are heavily scrutinised by the community, work across all platforms, and have several handy security features like indicating when a password has shown up in a breach, or is reused in your other accounts.
